// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiDu6FZ7jy7jf4SugaAjUv-8pt-NvKXms',
    appId: '1:389248325255:web:f9244d13c7e66c9c11ca22',
    messagingSenderId: '389248325255',
    projectId: 'memory-4f107',
    authDomain: 'memory-4f107.firebaseapp.com',
    storageBucket: 'memory-4f107.appspot.com',
    measurementId: 'G-T8C4K8SVPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBOSGKTYkOghXmGH3VVgvNiGsJaCmDQbM',
    appId: '1:389248325255:android:ffc91493e6cd737611ca22',
    messagingSenderId: '389248325255',
    projectId: 'memory-4f107',
    storageBucket: 'memory-4f107.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBROqXeAvBqpAX_YsRsT0LfGbABEB7x2z4',
    appId: '1:389248325255:ios:475789379f97ee7f11ca22',
    messagingSenderId: '389248325255',
    projectId: 'memory-4f107',
    storageBucket: 'memory-4f107.appspot.com',
    iosClientId: '389248325255-ffueob1pgslcg2q65tga60v6pr15hqi1.apps.googleusercontent.com',
    iosBundleId: 'com.example.memory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBROqXeAvBqpAX_YsRsT0LfGbABEB7x2z4',
    appId: '1:389248325255:ios:8eec55952b0b8c1411ca22',
    messagingSenderId: '389248325255',
    projectId: 'memory-4f107',
    storageBucket: 'memory-4f107.appspot.com',
    iosClientId: '389248325255-idfb9regpld073ashj0a5ugeuqpmc4vk.apps.googleusercontent.com',
    iosBundleId: 'com.example.memory.RunnerTests',
  );
}
